# Generated by Django 3.2.5 on 2021-07-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='default.png', max_length=150),
            preserve_default=False,
        ),
    ]
