# Generated by Django 3.2.5 on 2021-07-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='profilePicName',
            field=models.CharField(default='default.png', max_length=100),
        ),
    ]
