# Generated by Django 3.2.5 on 2021-07-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20210710_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='Post description'),
        ),
    ]
